-- USERS
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Gloria', '6004', 'gloria@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/ilya-mondryk-MqE3tHPPW6s-unsplash_wp9s8c.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Lilly', '6004', 'lilly@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/zahra-amiri-sKT0YQDftBU-unsplash_f6ggvf.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Tim', '6004', 'tim@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/kadyn-pierce-hLdPivE3NwM-unsplash_pp6zq3.jpg', now(), now()); 
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Bora', '6004', 'bora@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/tabitha-turner-m23xEObdoY8-unsplash_gmqrph.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Lina', '6004', 'lina@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/junior-reis-PJTm6LbXx7E-unsplash_c8ok0r.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Ali', '6004', 'ali@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/awab-husameldin-5wn6DeAEcmE-unsplash_zljtzp.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Laura', '6004', 'laura@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/stefan-stefancik-QXevDflbl8A-unsplash_pijtqf.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Tina', '6004', 'tina@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/h-f-e-co-WhQveKOU2b4-unsplash_gslcqy.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Rose', '6004', 'rose@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/shayan-rti-uHDfNkNhsMQ-unsplash_rbiu4n.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Brad', '6004', 'brad@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/gift-habeshaw-xlNqj5Fd_5I-unsplash_oef1qo.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Rob', '6004', 'rob@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/dave-goudreau-s0PqnP3T4jo-unsplash_z7defj.jpg', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Lisa', '6004', 'lisa@gmail.com', '0400666000', 'abc', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/eleanor-4sVM2kQuk7I-unsplash_m1zqoa.jpg', now(), now());

-- Bakedgoods
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Cherry Cake', 'We took cherry pie to a whole new level as a frozen treat. With a luscious layer of chocolate fudge inside, this is one impressive pie.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/frosty-ilze-lD0JFJDXBfQ-unsplash_urswbd.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Quiche', 'Quiche is a French tart consisting of pastry crust filled with savoury custard and pieces of cheese, meat, seafood or vegetables.', 'eggs', 4, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/dilyara-garifullina-Uju0eqW7G7U-unsplash_a1dhhn.jpg', 4, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Zimtschnecken', 'Cinnamon is a spice obtained from the inner bark of several tree species from the genus Cinnamomum.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/beth-macdonald-V6LEV6CBVLw-unsplash_hmooch.jpg', 1,now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Strosemmel', 'German recipes A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment.', 'eggs, flour', 5, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/sergio-arze-cWXibBbXx44-unsplash_xsio2v.jpg', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Cookies', 'A chocolate chip cookie is a drop cookie that features chocolate chips or chocolate morsels as its distinguishing ingredient.', 'eggs', 4, 1, 0, 0, 1, 0, 0, 4,'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/food-photographer-jennifer-pallian-OfdDiqx8Cz8-unsplash_jztlld.jpg', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Scones', 'A scone is a baked good, usually made of either wheat or oatmeal with baking powder as a leavening agent, and baked on sheet pans.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/alexandra-kusper-r32FhiD1ltc-unsplash_mo8zre.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Bun', 'A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment. ', 'oil, eggs', 3, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/victoria-shes-IUk1S6n2s0o-unsplash_ueukcy.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Wholemeal Bread', 'Whole wheat bread or wholemeal bread is a type of bread made using flour that is partly or entirely milled from whole or almost-whole wheat grains, see whole-wheat flour and whole grain.', 'wholemeal, eggs', 3, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/monika-grabkowska-nVoDL1YDWRE-unsplash_wjdlcg.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Lemon Tart', 'A traditional French-style lemon tart with creamy, dreamy lemon curd filling, that tastes just like the ones in Paris. It’s my mom’s recipe and has been a favorite in my family for years.', 'eggs', 3, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/frosty-ilze-lD0JFJDXBfQ-unsplash_urswbd.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Baguette', 'A baguette is a long, thin type of bread of French origin that is commonly made from basic lean dough. It is distinguishable by its length and crisp crust.', 'eggs', 2, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664548/ShareYourBaked/bakedgoods/dilyara-garifullina-A2JYED-VlxA-unsplash_s9mpbz.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Cream Tart', 'These Cream Tarts are all the rage! Also known as cream biscuits or cream cakes, they’re a beautiful and unique twist on traditional cakes.', 'eggs', 2, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/brooke-lark-V4MBq8kue3U-unsplash_h9rvz2.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Macaron', 'This easy French macaron recipe makes a batch of the most dainty, delicate, and delicious cookies that will float right into your mouth and disappear.', 'sugar, eggs', 5, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/chelsea-audibert-hV1gChgMa-k-unsplash_v9eyau.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Shortbread', 'Shortbread is a traditional Scottish biscuit usually made from one part white sugar, two parts butter, and either three parts oat flour or four parts plain wheat flour.', 'flour, eggs, butter', 5, 1, 0, 0, 1, 0, 0, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620665022/ShareYourBaked/bakedgoods/razvan-mirel-_k-ixIDtbJI-unsplash_chrm1q.jpg', 2, now(), now());


-- for mysql
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Cherry Cake', 'We took cherry pie to a whole new level as a frozen treat. With a luscious layer of chocolate fudge inside, this is one impressive pie.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/frosty-ilze-lD0JFJDXBfQ-unsplash_urswbd.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Quiche', 'Quiche is a French tart consisting of pastry crust filled with savoury custard and pieces of cheese, meat, seafood or vegetables.', 'eggs', 4, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/dilyara-garifullina-Uju0eqW7G7U-unsplash_a1dhhn.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Zimtschnecken', 'Cinnamon is a spice obtained from the inner bark of several tree species from the genus Cinnamomum.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/beth-macdonald-V6LEV6CBVLw-unsplash_hmooch.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Strosemmel', 'German recipes A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment.', 'eggs, flour', 5, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/sergio-arze-cWXibBbXx44-unsplash_xsio2v.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Cookies', 'A chocolate chip cookie is a drop cookie that features chocolate chips or chocolate morsels as its distinguishing ingredient.', 'eggs', 4, 1, 0, 0, 1, 0, 0, 4,'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/food-photographer-jennifer-pallian-OfdDiqx8Cz8-unsplash_jztlld.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Scones', 'A scone is a baked good, usually made of either wheat or oatmeal with baking powder as a leavening agent, and baked on sheet pans.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/alexandra-kusper-r32FhiD1ltc-unsplash_mo8zre.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Bun', 'A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment. ', 'oil, eggs', 3, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/victoria-shes-IUk1S6n2s0o-unsplash_ueukcy.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Wholemeal Bread', 'Whole wheat bread or wholemeal bread is a type of bread made using flour that is partly or entirely milled from whole or almost-whole wheat grains, see whole-wheat flour and whole grain.', 'wholemeal, eggs', 3, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/monika-grabkowska-nVoDL1YDWRE-unsplash_wjdlcg.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Lemon Tart', 'A traditional French-style lemon tart with creamy, dreamy lemon curd filling, that tastes just like the ones in Paris. It’s my mom’s recipe and has been a favorite in my family for years.', 'eggs', 3, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/frosty-ilze-lD0JFJDXBfQ-unsplash_urswbd.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Baguette', 'A baguette is a long, thin type of bread of French origin that is commonly made from basic lean dough. It is distinguishable by its length and crisp crust.', 'eggs', 2, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664548/ShareYourBaked/bakedgoods/dilyara-garifullina-A2JYED-VlxA-unsplash_s9mpbz.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Cream Tart', 'These Cream Tarts are all the rage! Also known as cream biscuits or cream cakes, they’re a beautiful and unique twist on traditional cakes.', 'eggs', 2, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/brooke-lark-V4MBq8kue3U-unsplash_h9rvz2.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Macaron', 'This easy French macaron recipe makes a batch of the most dainty, delicate, and delicious cookies that will float right into your mouth and disappear.', 'sugar, eggs', 5, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/chelsea-audibert-hV1gChgMa-k-unsplash_v9eyau.jpg', now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt) VALUES ('Shortbread', 'Shortbread is a traditional Scottish biscuit usually made from one part white sugar, two parts butter, and either three parts oat flour or four parts plain wheat flour.', 'flour, eggs, butter', 5, 1, 0, 0, 1, 0, 0, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620665022/ShareYourBaked/bakedgoods/razvan-mirel-_k-ixIDtbJI-unsplash_chrm1q.jpg', now(), now());

-- Jawdb

INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Gloria', '6004', 'gloria@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/ilya-mondryk-MqE3tHPPW6s-unsplash_wp9s8c.jpggloria@gmail.comgloria@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/ilya-mondryk-MqE3tHPPW6s-unsplash_wp9s8c.jpggloria@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Lilly', '6004', 'lilly@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/zahra-amiri-sKT0YQDftBU-unsplash_f6ggvf.jpglilly@gmail.comlilly@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/zahra-amiri-sKT0YQDftBU-unsplash_f6ggvf.jpglilly@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Tim', '6004', 'tim@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/kadyn-pierce-hLdPivE3NwM-unsplash_pp6zq3.jpgtim@gmail.comtim@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/kadyn-pierce-hLdPivE3NwM-unsplash_pp6zq3.jpgtim@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Bora', '6004', 'bora@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/tabitha-turner-m23xEObdoY8-unsplash_gmqrph.jpgbora@gmail.combora@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/tabitha-turner-m23xEObdoY8-unsplash_gmqrph.jpgbora@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Lina', '6004', 'lina@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/junior-reis-PJTm6LbXx7E-unsplash_c8ok0r.jpglina@gmail.comlina@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/junior-reis-PJTm6LbXx7E-unsplash_c8ok0r.jpglina@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Ali', '6004', 'ali@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/awab-husameldin-5wn6DeAEcmE-unsplash_zljtzp.jpgali@gmail.comali@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/awab-husameldin-5wn6DeAEcmE-unsplash_zljtzp.jpgali@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Laura', '6004', 'laura@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/stefan-stefancik-QXevDflbl8A-unsplash_pijtqf.jpglaura@gmail.comlaura@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/stefan-stefancik-QXevDflbl8A-unsplash_pijtqf.jpglaura@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Tina', '6004', 'tina@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/h-f-e-co-WhQveKOU2b4-unsplash_gslcqy.jpgtina@gmail.comtina@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/h-f-e-co-WhQveKOU2b4-unsplash_gslcqy.jpgtina@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Rose', '6004', 'rose@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/shayan-rti-uHDfNkNhsMQ-unsplash_rbiu4n.jpgrose@gmail.comrose@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653996/ShareYourBaked/users/shayan-rti-uHDfNkNhsMQ-unsplash_rbiu4n.jpgrose@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Rob', '6004', 'rob@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/dave-goudreau-s0PqnP3T4jo-unsplash_z7defj.jpgrob@gmail.comrob@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/dave-goudreau-s0PqnP3T4jo-unsplash_z7defj.jpgrob@gmail.com', now(), now());
INSERT INTO users (name, postCode, email, phoneNumber, password, imageUrl, createdAt, updatedAt) VALUES ('Lisa', '6004', 'lisa@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/eleanor-4sVM2kQuk7I-unsplash_m1zqoa.jpglisa@gmail.comlisa@gmail.com', '0400666000', '2gXWr81Vul/Z.wI5Ce9.NLmCMUHVFzBKAYQ5OZXS', 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620653995/ShareYourBaked/users/eleanor-4sVM2kQuk7I-unsplash_m1zqoa.jpglisa@gmail.com', now(), now());


-- Jawdb
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Cherry Cake', 'We took cherry pie to a whole new level as a frozen treat. With a luscious layer of chocolate fudge inside, this is one impressive pie.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/frosty-ilze-lD0JFJDXBfQ-unsplash_urswbd.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Quiche', 'Quiche is a French tart consisting of pastry crust filled with savoury custard and pieces of cheese, meat, seafood or vegetables.', 'eggs', 4, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/dilyara-garifullina-Uju0eqW7G7U-unsplash_a1dhhn.jpg', 4, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Zimtschnecken', 'Cinnamon is a spice obtained from the inner bark of several tree species from the genus Cinnamomum.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/beth-macdonald-V6LEV6CBVLw-unsplash_hmooch.jpg', 1,now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Strosemmel', 'German recipes A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment.', 'eggs, flour', 5, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/sergio-arze-cWXibBbXx44-unsplash_xsio2v.jpg', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Cookies', 'A chocolate chip cookie is a drop cookie that features chocolate chips or chocolate morsels as its distinguishing ingredient.', 'eggs', 4, 1, 0, 0, 1, 0, 0, 4,'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/food-photographer-jennifer-pallian-OfdDiqx8Cz8-unsplash_jztlld.jpg', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Scones', 'A scone is a baked good, usually made of either wheat or oatmeal with baking powder as a leavening agent, and baked on sheet pans.', 'eggs', 5, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/alexandra-kusper-r32FhiD1ltc-unsplash_mo8zre.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Bun', 'A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment. ', 'oil, eggs', 3, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/victoria-shes-IUk1S6n2s0o-unsplash_ueukcy.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Wholemeal Bread', 'Whole wheat bread or wholemeal bread is a type of bread made using flour that is partly or entirely milled from whole or almost-whole wheat grains, see whole-wheat flour and whole grain.', 'wholemeal, eggs', 3, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664550/ShareYourBaked/bakedgoods/monika-grabkowska-nVoDL1YDWRE-unsplash_wjdlcg.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Lemon Tart', 'A traditional French-style lemon tart with creamy, dreamy lemon curd filling, that tastes just like the ones in Paris. It’s my mom’s recipe and has been a favorite in my family for years.', 'eggs', 3, 1, 0, 0, 1, 0, 0, 2, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/frosty-ilze-lD0JFJDXBfQ-unsplash_urswbd.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Baguette', 'A baguette is a long, thin type of bread of French origin that is commonly made from basic lean dough. It is distinguishable by its length and crisp crust.', 'eggs', 2, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664548/ShareYourBaked/bakedgoods/dilyara-garifullina-A2JYED-VlxA-unsplash_s9mpbz.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Cream Tart', 'These Cream Tarts are all the rage! Also known as cream biscuits or cream cakes, they’re a beautiful and unique twist on traditional cakes.', 'eggs', 2, 1, 0, 0, 1, 0, 0, 4, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/brooke-lark-V4MBq8kue3U-unsplash_h9rvz2.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Macaron', 'This easy French macaron recipe makes a batch of the most dainty, delicate, and delicious cookies that will float right into your mouth and disappear.', 'sugar, eggs', 5, 1, 0, 0, 1, 0, 0, 3, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620664549/ShareYourBaked/bakedgoods/chelsea-audibert-hV1gChgMa-k-unsplash_v9eyau.jpg', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, UserId) VALUES ('Shortbread', 'Shortbread is a traditional Scottish biscuit usually made from one part white sugar, two parts butter, and either three parts oat flour or four parts plain wheat flour.', 'flour, eggs, butter', 5, 1, 0, 0, 1, 0, 0, 'https://res.cloudinary.com/dfp6vgn1q/image/upload/v1620665022/ShareYourBaked/bakedgoods/razvan-mirel-_k-ixIDtbJI-unsplash_chrm1q.jpg', 2, now(), now());