-- USERS
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber, password, createdAt, updatedAt) VALUES ('Simon', 'Gruber', '6002', 'Simon.Gruber@gmx.com', 'Simon123', 'Simon1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('John', 'McLaine', '6245', 'John@gmx.com', 'John123', 'John1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Bob', 'Thebuilder', '6008', 'Bob@gmx.com', 'Bob123', 'Bob1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Frank', 'Drabbin', '6001', 'Frank@gmx.com', 'Frank123', 'Frank1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('John', 'Rambo', '6025', 'John.Rambo@gmx.com', 'JohnR123', 'JohnR1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Evelyn', 'Salt', '6100', 'Evelyn@gmx.com', 'Evelyn123', 'Evelyn1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('James', 'Belushi', '6024', 'Belushi@gmx.com', 'Belushi123', 'Belushi1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Edard', 'Stark', '6325', 'Edard@gmx.com', 'Edard123', 'Edard1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Harry', 'Potter', '6354', 'Harry@gmx.com', 'Harry123', 'Harry1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Ron', 'Wesley', '6087', 'Ron@gmx.com', 'Ron123', 'Ron1234', now(), now());
INSERT INTO users (firstname, lastname, postcode, email, phoneNumber password, createdAt, updatedAt) VALUES ('Nadja', 'Flam', '6051', 'nadja.flam@gmx.net', 'NFlma', 'NFlma', now(), now());

-- Bakedgoods
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Cookies', 'It is very delicious', 'eggs, butter', 4, 1, 0, 0, 1, 0, 0, 4, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 1, now(), now(), 1);
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Cherry Cake', 'Taste yummy', 'eggs', 5, 1, 0, 0, 1, 0, 0, 2, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80',2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Quiche', 'Very nice', 'egg,', 4, 1, 0, 0, 1, 0, 0, 3, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Zimtschnecken', 'Golden brown', 'cinnamon', 5, 1, 0, 0, 1, 0, 0, 4, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Strosemmel', 'German recipes', 'flour', 5, 1, 0, 0, 1, 0, 0, 2, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 1, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Scones', 'So sweet', 'butter', 5, 1, 0, 0, 1, 0, 0, 3, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Bun', 'It is very yummy', 'oil', 3, 1, 0, 0, 1, 0, 0, 4, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Wholemeal Bread', 'Good for morning breakfast', 'wholemeal', 3, 1, 0, 0, 1, 0, 0, 3, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 1, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Lemon Tart', 'Nice lemon flavour', 'Lemon', 3, 1, 0, 0, 1, 0, 0, 2, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 2, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Bugett', 'It is very delicious', 'butter', 2, 1, 0, 0, 1, 0, 0, 4, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Creme Tart', 'Irresistable', 'creme', 2, 1, 0, 0, 1, 0, 0, 4, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 1, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Macaron', 'So delicious', 'sugar', 5, 1, 0, 0, 1, 0, 0, 3, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 3, now(), now());
INSERT INTO bakedgoods (recipename, description, ingredience, pieces, nuts, glutenfree, vegan, vegetarian, dairyfree, halal, category, imgurl, createdAt, updatedAt, userId) VALUES ('Shortbread', 'Like my Grandma made them', 'flour', 5, 1, 0, 0, 1, 0, 0, 'https://images.unsplash.com/photo-1609126979532-0f514232d1a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80', 3, now(), now());
